HMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hotel.urls')),
    path('accounts/', include('allauth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hotel/urls.py
from django.urls import path
from .views import RoomListView, BookingList, BookingView, RoomDetailView

app_name='hotel'

urlpatterns = [
    path('room_list/',RoomListView,name='RoomList'),
    path('booking_list/',BookingList.as_view(),name='BookingList'),
    path('book/', BookingView.as_view(),name='BookingView'),
    path('room/<category>/', RoomDetailView.as_view(),name='RoomDetailView'),
]

hotel/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class Room(models.Model):

    ROOM_CATEGORIES = (
        ('YAC','AC'),
        ('NAC','NON-AC'),
        ('DEL','DELUXE'),
        ('KIN','KING'),
        ('QUE','QUEEN'),
    )
    number = models.IntegerField()
    category = models.CharField(max_length=3, choices=ROOM_CATEGORIES)
    beds = models.IntegerField()
    capacity = models.IntegerField()

    def __str__(self):
        return f'{self.number}. {self.category} with {self.beds} for {self.capacity} peaople'

class Booking(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    room = models.ForeignKey(Room,on_delete=models.CASCADE)
    check_in = models.DateTimeField()
    check_out = models.DateTimeField()

    def __str__(self):
        return f"{self.user} has booked {self.room} from {self.check_in} to {self.check_out}"

hotel/forms.py
from django import forms

class AvailabilityForm(forms.Form):
    check_in = forms.DateTimeField(required=True, input_formats=["%Y-%m-%dT%H:%M", ])
    check_out = forms.DateTimeField(required=True, input_formats=["%Y-%m-%dT%H:%M", ])

hotel/views.py
from django.shortcuts import render, HttpResponse
from django.views.generic import ListView, FormView, View
from django.urls import reverse
from .models import Room, Booking
from .forms import AvailabilityForm
from hotel.booking_functions.availability import check_availability
# Create your views here.

def RoomListView(request):
    room = Room.objects.all()[0]
    room_categories = dict(room.ROOM_CATEGORIES)
    room_values = room_categories.values()
    room_list = []
    for room_category in room_categories:
        room = room_categories.get(room_category)
        room_url = reverse('hotel:RoomDetailView', kwargs={'category':room_category})
        room_list.append((room, room_url))
    context={'room_list':room_list,}

    return render(request,'room_list_view.html', context)

class BookingList(ListView):
    model = Booking

class RoomDetailView(View):
    def get(self, request, *args, **kwargs):
        category = self.kwargs.get('category', None)
        form = AvailabilityForm()
        room_list = Room.objects.filter(category=category)

        if len(room_list)>0:
            room = room_list[0]
            room_category = dict(room.ROOM_CATEGORIES).get(room.category)
            context = {
                'room_category': room_category,
                'form':form,
            }
            return render(request,'room_detail_view.html', context)
        else:
            return HttpResponse('Category does not exist')

    def post(self, request, *args, **kwargs):
        category = self.kwargs.get('category', None)
        room_list = Room.objects.filter(category=category)
        form = AvailabilityForm(request.POST)

        if form.is_valid():
            data = form.cleaned_data

        available_rooms = []
        for room in room_list:
            if check_availability(room, data['check_in'], data['check_out']):
                available_rooms.append(room)

        if len(available_rooms) > 0:
            room = available_rooms[0]
            booking = Booking.objects.create(
                user=self.request.user,
                room=room,
                check_in=data['check_in'],
                check_out=data['check_out']
            )
            booking.save()
            return HttpResponse(booking)
        else:
            return HttpResponse('All of this category of rooms are booked!! Try another one')

class BookingView(FormView):
    form_class = AvailabilityForm
    template_name = 'availability_form.html'

    def form_valid(self, form):
        data = form.cleaned_data
        room_list = Room.objects.filter(category=data['room_category'])
        available_rooms = []
        for room in room_list:
            if check_availability(room, data['check_in'],data['check_out']):
                available_rooms.append(room)
        if len(available_rooms) > 0 :

            room = available_rooms[0]
            booking = Booking.objects.create(
                user = self.request.user,
                room = room,
                check_in = data['check_in'],

                check_out = data['check_out'],
            )
            booking.save()
            return HttpResponse(booking)
        else:
            return HttpResponse('This category of rooms are booked.')

hotel/templates/availability_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Book a room</title>
</head>
<body>
  <form action="" method="POST">
    {{form.as_p}}
      {% csrf_token %}
    <button type="submit">Book Room</button>

  </form>
</body>
</html>

hotel/templates/hotel/booking_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Booking List</title>
</head>
<body>
    {% for booking in booking_list %}
    <h2>{{booking}}</h2>
    {%endfor%}
</body>
</html>

hotel/templates/hotel/room_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Room List</title>
</head>
<body>
{% for room in room_list %}
    <h2>{{room}}</h2>
    {%endfor%}
</body>
</html>

hotel/templates/room_detail_view.html
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Room Detail</title>
    <script src="https://kit.fontawesome.com/692189991f.js" crossorigin="anonymous"></script>

    <!-- Main StyleSheet -->
    <link rel="stylesheet" href="{% static 'hotel/css/detail.css' %}">

</head>

<body>

    <!-- Main Content -->
    <div class="content">

        <!-- Room Image -->
        <div class="image">
            <img
                src="https://images.unsplash.com/photo-1519710164239-da123dc03ef4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60">
        </div>

        <!-- Room Details -->
        <div class="room">

            <!-- Div 1: Back to Home -->
            <div class="home">
                <a href="{% url 'hotel:RoomList' %}"><i class="fas fa-arrow-alt-circle-left">Home</i></a>
            </div>

            <!-- Div 2: Room Information -->
            <div class="room-info">
                <h1>{{room_category}}</h1>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Id optio rem saepe culpa architecto tempora
                    numquam debitis reiciendis! Quaerat laudantium consequuntur doloribus quod placeat consectetur
                    veniam,
                    rerum repellendus magnam labore. </p>
            </div>

            <!-- Div 3: Room Booking Form -->
            <form id="booking-form" action="" method="POST">

                {% csrf_token %}

                <!-- Input Div -->
                <div class="input-div">
                    <label for="id_check_in">Check In : </label>
                    <input type="datetime-local" id="id_check_in" name="check_in">
                </div>

                <!-- Input Div -->
                <div class="input-div">
                    <label for="id_check_out">Check Out : </label>
                    <input type="datetime-local" id="id_check_out" name="check_out">
                </div>

                <!-- Input Div -->
                <div class="input-div">
                    <button type="submit">Book the Room</button>
                </div>

            </form>

        </div> <!-- END Room Div -->

    </div> <!-- END Main Content Div -->

</body>

</html>

hotel/templates/room_list_view.html
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hotelina</title>
    <!-- Main StyleSheet -->
    <link rel="stylesheet" href="{% static 'hotel/css/home.css' %}">
</head>

<body>
    <!-- Brand -->
    <h1 id="brand">Hotelina</h1>

    <!-- Main Content -->
    <div class="content">
        {% for room_category, room_url in room_list%}
        <div class="room">
            <a href="{{room_url}}">
                <img
                    src="https://images.unsplash.com/photo-1519710164239-da123dc03ef4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60">

                <h2>{{room_category}}</h2>
                <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi</p>
            </a>
        </div>
        {% endfor %}
    </div>
</body>

</html>